### ISSUE TITLE
Disabling entities?

### ISSUE THREAD

**Issue by lukemcraig** [andoowhy/EgoCS#12]
With normal monobehaviours, if you disable the GameObject, it's monobehavior scripts stop calling their Update() loops. Is there a good way to do this with EgoCS's Systems so they automatically skip disabled entities? I suppose I could put
```
		constraint.ForEachGameObject( ( egoComponent, transform, movement ) =>
			{
				if (!egoComponent.gameObject.activeInHierarchy)
					return; 
```
before all my logic, but I wasn't sure if there was a better way.

**Comment by andoowhy** [comment]
You _could_ check for enabled / disabled GameObjects that way, but I don't recommend it.

Instead, I suggest creating various ```*Enabled``` Component types and attaching them to relevant GameObjects. In your example, for every ```Movement``` Component, you could also attach a ```MovementEnabled``` Component, and make sure your relevant ```Movement``` System also includes that ```MovementEnabled``` Component in its Constraint.

While it might be more work and seem like unnecessary boilerplate, this allows for different _kinds_ of enabling & disabling. For example, any given GameObject could have any combination of ```InputEnabled```, ```MovementEnabled```, and ```AnimationEnabled``` Components attached. The GameObject itself always exists and is enabled, but different intended functionality on it is clearly defined.

Following this, along with a regular ```MovementSystem```, you could then create two more Systems (```EnableMovementSystem``` and ```DisableMovementSystem```) whose sole jobs are to enable and disable, respectively, relevant GameObjects by attaching and detaching ```MovementEnabled``` Components.

**Comment by lukemcraig** [comment]
@andoowhy Thanks for your response! I see that `MovementSystem `would stop matching this Entity because it wouldn't have the `MovementEnabled `component anymore _(but on the following frame, if it was removed by a preceding system, right?)_. This way I wouldn't have to duplicate my check in all my systems. 

In my particular case, I'm deactivating this GameObject as a response to it colliding with an obstacle. It's effectively being destroyed, but I have a reverse time mechanic so I don't actually want to destroy it, in case I want to restore it. So I need to swap out every single `*Enabled` component on this Entity. However, the `ObstacleCollisionSystem ` won't know all the `*Enabled` components that need to be swapped out on the Entity that's being disabled. 

I suppose a solution to that would be to make a `DisableAllDisableableComponents: EgoEvent`, which stores the `EgoComponent `of the Entity that needs to disable, and have my `ObstacleCollisionSystem `create a `DisableAllDisableableComponents` event on collision. Then the `DisableMovementSystem` and every other system that corresponds with a  `*Enabled` component can have a handler for `DisableAllDisableableComponents`, which then does the actual swapping.

This way, if I only want to disable the Movement, I can, but I can also disable the entire entity. What do you think, is this a good way to design it in the context of EgoCS?

**Comment by andoowhy** [comment]
You should create several systems whose sole job is to handle obstacle collision events and disable the relevant ```*Enabled``` Component. ```ObstacleCollisionDisableInputSystem```, ```ObstacleCollisionDisableAnimationSystem```, etc.

**Comment by lukemcraig** [comment]
Wow ok I'll try that, thanks.
