### ISSUE TITLE
Feature Request: Entity Assemblages/Blueprints

### ISSUE THREAD

**Issue by benoneal** [andoowhy/EgoCS#3]
One thing I've found really handy in other ECS libraries is the convenience of Assemblages/Blueprints. Basically they are Entity factories which are super handy for creating common Entity types, like "soldier", "supersoldier", "tank", and even "player" (in multiplayer games). 

The key thing though is that these Blueprints/Assemblages can construct their entities based on data passed in from JSON/XML/CSV, making it much easier for designers to create and tweak new entities without having to get a programmer to implement every change. 

I'd find that sort of thing to be really valuable when using EgoCS.

**Comment by andoowhy** [comment]
I have no plans to add this functionality. EgoCS on its own aims to stay as close to the built-in Unity3D workflow, for better or worse. It's just Unity3D (GameObjects + Components) + Systems + Events.

Similar functionality, although admittedly less flexible, exits using Unity prefabs and tweaking their values in the Inspector.

If you know of another established "Blueprints/Assemblages" library, I can see if I can get EgoCS to play nice with it (no promises, though).
