### ISSUE TITLE
Feature Request: Add/Remove components, access Entities

### ISSUE THREAD

**Issue by benoneal** [andoowhy/EgoCS#4]
One thing I've see a lot in other ECS implementations is the ability to add or remove components from entities as they flow through systems. Some examples include removing movement components to freeze entities, adding "hostile" components to make entities attackable/aggressive, placing and removing debuffs from targets, etc. 

But I can't see any simple way to do this with EgoCS. This wouldn't inherently be such a big deal, except that I also can't see any way to get a component's Entity (GameObject), which I could have used to addComponents to... 

For the project I'm working on now, these things are kind of crucial.

**Comment by andoowhy** [comment]
Please see [this page](https://github.com/andoowhy/EgoCS/wiki/Creating-and-Destroying-GameObjects-and-Components) on the wiki.
