### ISSUE TITLE
EgoCS + UniRx

### ISSUE THREAD

**Issue by tkaczz** [andoowhy/EgoCS#8]
Hi, I'm new to EgoCS and UniRX but I want to learn new things.

Is EgoCS would work with reactive/observable fields in POCO's components? I think that can be problem with GameObjects/MonoBehavoiurs created in runtime, but I hope that I'm wrong.

**Comment by andoowhy** [comment]
I don't think Ego will play nicely out of the box with UniRX. They're both "Big Idea" frameworks that assume you're following their architecture to a tee and that they're the only way of controlling your game.

Try implementing the same small game with EgoCS and UniRX, and go with the one you like. Whenever I'm learning a new engine or framework, I implement a Breakout clone. [There's already one for EgoCS.](https://github.com/andoowhy/BreakoutWithEgoCS)
